### ISSUE TITLE
Failed Instance Resolution for State

### ISSUE THREAD

**Issue by pseudonom** [purescript/purescript-transformers#28] opened 2015-02-25 06:56 UTC
If I define

```purescript
module Foo where

import qualified Control.Monad.State as ST
import qualified Control.Monad.State.Class as ST

ident :: forall a. a -> a
ident a = a
ident' :: Number -> Number
ident' a = a
```
then
```purescript
a :: ST.State Number Unit
a = ST.modify ident'
```
compiles/works fine.

However, 

```purescript
a :: ST.State Number Unit
a = ST.modify ident
```

complains that 

```
No instance found for Control.Monad.State.Class.MonadState u7 (Control.Monad.State.Trans.StateT Prim.Number Data.Identity.Identity)
```
.

(Both versions work in Haskell.)

**Comment by hdgarrood** [comment] 2015-12-10 01:38
I think the solution to this might be functional dependencies, which would make this a duplicate of https://github.com/purescript/purescript/issues/1580. Not entirely sure, though.

**Comment by garyb** [comment] 2016-10-10 01:45
I'm pretty sure this is related to the lack of functional dependencies too, so this should be fixed in the next release.

**Closed by garyb** 2016-10-10 01:45 UTC
